/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.PortfolioManager.businessGUI.portfolioManagement.gui;

import com.PortfolioManager.domain.dao.IAccountDAO;
import com.PortfolioManager.domain.dao.IPortfolioDAO;
import com.PortfolioManager.domain.entities.OrderStock;
import com.PortfolioManager.domain.entities.Portfolio;
import com.PortfolioManager.domain.entities.Stock;
import com.PortfolioManager.domain.impl.AccountDAO;
import com.PortfolioManager.domain.impl.PortfolioDAO;
import com.PortfolioManager.businessGUI.portfolioManagement.performance.data.PortfolioPerformanceUtilities;
import com.gui.mainGUI.GUI;
import com.gui.mainGUI.splash.ImageHelper;
import java.awt.Color;
import java.math.BigDecimal;
import java.text.DateFormat;
import java.util.Date;
import java.util.StringTokenizer;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author Ahmed
 */
public class OrderBuy extends javax.swing.JFrame {

    /**
     * Creates new form OrderBuy
     */
    public static OrderBuy orderBuy = null;
    public static IPortfolioDAO iPortfolioDAO = new PortfolioDAO();
    public static IAccountDAO iAccountDAO = new AccountDAO();
    private static Portfolio portfolio;
    private MaskFormatter moneyMask;
    private static Stock stock;
    private static Color agrColor;
    private static Color conColor;
    private static Color balColor;
    private static boolean moneyError;
    
    public static double moneyReader(String moneyString) {
        StringTokenizer st = new StringTokenizer(moneyString, ",");
        if (moneyString.contains("$")) {
            return 0.0;
        } else {
            double money = Double.parseDouble(st.nextToken()) * 1000;
            money += Double.parseDouble(st.nextToken());
            return money;
        }
    }
    
    public static double roundDBL(double dollars) {
        int decimalPlace = 6;
        BigDecimal bd = new BigDecimal(dollars);
        bd = bd.setScale(decimalPlace, BigDecimal.ROUND_UP);
        
        return (bd.doubleValue());
    }
    
    public static String moneyWriter(double moneyValue) {
        String money = "";
        int millions = (int) moneyValue / 1000;
        money += millions + ",";
        double dollars = moneyValue - millions * 1000;
        dollars = roundDBL(dollars);
        if (dollars < 10) {
            money += "00" + dollars;
        } else if (dollars < 100) {
            money += "0" + dollars;
        } else {
            money += "" + dollars;
        }
        return money;
    }
    
    public static void refresher() {
        
        portfolio = GUI.getMe().getLoggedInvestor().getAccount()
                .getPortfolio();
        Stock stockaux = GUI.getMe().getStock();
        stock = new Stock();
        stock.setBuyPrice(stockaux.getBuyPrice());
        stock.setCurrentPrice(stockaux.getBuyPrice());
        stock.setSymbol(stockaux.getSymbol());
        stock.setName(stockaux.getName());

        jtf_stockQuantity.setSelectedIndex(0);
        jtf_stockPrice.setText(moneyWriter(stock.getCurrentPrice()));
        jtfInvestedMoney.setText(moneyWriter(portfolio.getInvestedMoney()));
        jtfBeta.setText(roundDBL(stock.getBeta()) + "");
        DateFormat df = DateFormat.getDateInstance(DateFormat.LONG);
        String dt = df.format(new Date());
        jtfDate.setText(dt);
        jtfMarket.setText(portfolio.getMarket().getMarketId());
        jtfPerformance.setText(roundDBL(portfolio.getPortfolioPerformance()) + "");
        jtfStock.setText(stock.getName());
        jtfAgr.setBackground(agrColor);
        jtfCon.setBackground(conColor);
        jtf_balance.setBackground(balColor);
        moneyError = false;
        totalPriceCalculator();
    }
    
    private OrderBuy() {
        initComponents();
        setIconImage(ImageHelper.loadImage("/com/gui/img/Contract.png").getImage());
        agrColor = jtfAgr.getBackground();
        conColor = jtfCon.getBackground();
    }
    
    public static OrderBuy getMe() {
        if (orderBuy == null) {
            orderBuy = new OrderBuy();
        }
        refresher();
        return orderBuy;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtfStock = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtf_stockPrice = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtfMarket = new javax.swing.JTextField();
        btnBeta = new javax.swing.JButton();
        jtfBeta = new javax.swing.JTextField();
        jtfAgr = new javax.swing.JTextField();
        jtfCon = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtf_stockPrice1 = new javax.swing.JTextField();
        jtfDate = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtf_stockQuantity = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jtf_balance = new javax.swing.JTextField();
        jtfInvestedMoney = new javax.swing.JTextField();
        jtfPerformance = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        btnQuit = new javax.swing.JButton();
        btnWriteContract = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("New Stock Contract");
        setAlwaysOnTop(true);
        setMinimumSize(new java.awt.Dimension(500, 415));
        setResizable(false);

        jPanel1.setMaximumSize(new java.awt.Dimension(483, 393));
        jPanel1.setMinimumSize(new java.awt.Dimension(483, 393));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Stock Specifications:"));

        jLabel1.setText("Stock:");

        jtfStock.setEditable(false);
        jtfStock.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfStock.setMaximumSize(new java.awt.Dimension(210, 20));
        jtfStock.setMinimumSize(new java.awt.Dimension(210, 20));
        jtfStock.setPreferredSize(new java.awt.Dimension(210, 20));

        jLabel2.setText("Price:");

        jtf_stockPrice.setEditable(false);
        jtf_stockPrice.setMaximumSize(new java.awt.Dimension(210, 20));
        jtf_stockPrice.setMinimumSize(new java.awt.Dimension(210, 20));
        jtf_stockPrice.setPreferredSize(new java.awt.Dimension(210, 20));

        jLabel3.setText("Bench Market:");

        jtfMarket.setEditable(false);
        jtfMarket.setMaximumSize(new java.awt.Dimension(121, 20));
        jtfMarket.setMinimumSize(new java.awt.Dimension(121, 20));
        jtfMarket.setPreferredSize(new java.awt.Dimension(121, 20));

        btnBeta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gui/img/psw-beta-icon.png"))); // NOI18N
        btnBeta.setToolTipText("Calculate Stock Beta");
        btnBeta.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBeta.setBorderPainted(false);
        btnBeta.setMaximumSize(new java.awt.Dimension(64, 64));
        btnBeta.setMinimumSize(new java.awt.Dimension(64, 64));
        btnBeta.setPreferredSize(new java.awt.Dimension(64, 64));
        btnBeta.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gui/img/psw-beta-icon.png"))); // NOI18N
        btnBeta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBetaMouseClicked(evt);
            }
        });

        jtfBeta.setEditable(false);
        jtfBeta.setToolTipText("To Calculate Click on BETA Button!");
        jtfBeta.setMaximumSize(new java.awt.Dimension(64, 20));
        jtfBeta.setMinimumSize(new java.awt.Dimension(64, 20));
        jtfBeta.setPreferredSize(new java.awt.Dimension(64, 20));

        jtfAgr.setEditable(false);
        jtfAgr.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfAgr.setText("Agressif");
        jtfAgr.setToolTipText("Agressif Stock behaviour comparing to bench market mouvement. (More Risky)");
        jtfAgr.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, new java.awt.Color(0, 102, 153), java.awt.Color.gray, new java.awt.Color(51, 153, 255)));
        jtfAgr.setMaximumSize(new java.awt.Dimension(64, 20));
        jtfAgr.setMinimumSize(new java.awt.Dimension(64, 20));
        jtfAgr.setPreferredSize(new java.awt.Dimension(64, 20));

        jtfCon.setEditable(false);
        jtfCon.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfCon.setText("Conservatif");
        jtfCon.setToolTipText("Conservatif Stock behaviour comparing to bench market mouvement. (Less Risky)");
        jtfCon.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, new java.awt.Color(0, 102, 153), java.awt.Color.gray, new java.awt.Color(51, 153, 255)));
        jtfCon.setMaximumSize(new java.awt.Dimension(64, 20));
        jtfCon.setMinimumSize(new java.awt.Dimension(64, 20));
        jtfCon.setPreferredSize(new java.awt.Dimension(64, 20));

        jLabel4.setText("Beta :");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 153, 255), java.awt.Color.lightGray));

        jLabel14.setText("$");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfBeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfMarket, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtfStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtf_stockPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(47, 47, 47)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(btnBeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfAgr, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                            .addComponent(jtfCon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jtfAgr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBeta, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfCon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(jtf_stockPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14))))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jtfMarket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jtfBeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Contract Specifications:"));

        jLabel8.setText("Date:");

        jLabel6.setText("Stock Lot:");

        jtf_stockPrice1.setEditable(false);
        jtf_stockPrice1.setMaximumSize(new java.awt.Dimension(130, 20));
        jtf_stockPrice1.setMinimumSize(new java.awt.Dimension(130, 20));
        jtf_stockPrice1.setPreferredSize(new java.awt.Dimension(130, 20));

        jtfDate.setEditable(false);
        jtfDate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfDate.setMaximumSize(new java.awt.Dimension(130, 20));
        jtfDate.setMinimumSize(new java.awt.Dimension(130, 20));
        jtfDate.setPreferredSize(new java.awt.Dimension(130, 20));

        jLabel7.setText("Price:");

        jtf_stockQuantity.setMaximumRowCount(4);
        jtf_stockQuantity.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "10", "20", "40", "80" }));
        jtf_stockQuantity.setMaximumSize(new java.awt.Dimension(38, 22));
        jtf_stockQuantity.setMinimumSize(new java.awt.Dimension(38, 22));
        jtf_stockQuantity.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jtf_stockQuantityItemStateChanged(evt);
            }
        });

        jLabel12.setText("$");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(22, 22, 22))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jtf_stockPrice1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtfDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jtf_stockQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jtfDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jtf_stockPrice1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jtf_stockQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Portfolio:"));

        jLabel5.setText("Liquid Money:");

        jLabel9.setText("Invested Money:");

        jLabel10.setText("Performance:");

        jtf_balance.setEditable(false);
        jtf_balance.setMaximumSize(new java.awt.Dimension(100, 20));
        jtf_balance.setMinimumSize(new java.awt.Dimension(100, 20));
        jtf_balance.setPreferredSize(new java.awt.Dimension(100, 20));

        jtfInvestedMoney.setEditable(false);
        jtfInvestedMoney.setMaximumSize(new java.awt.Dimension(100, 20));
        jtfInvestedMoney.setMinimumSize(new java.awt.Dimension(100, 20));
        jtfInvestedMoney.setPreferredSize(new java.awt.Dimension(100, 20));

        jtfPerformance.setEditable(false);
        jtfPerformance.setMaximumSize(new java.awt.Dimension(100, 20));
        jtfPerformance.setMinimumSize(new java.awt.Dimension(100, 20));
        jtfPerformance.setPreferredSize(new java.awt.Dimension(100, 20));

        jLabel13.setText("$");

        jLabel11.setText("$");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtf_balance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfInvestedMoney, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfPerformance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtf_balance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jtfInvestedMoney, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jtfPerformance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, new java.awt.Color(0, 102, 153), java.awt.Color.gray, new java.awt.Color(51, 153, 255)));
        jPanel5.setMaximumSize(new java.awt.Dimension(483, 104));
        jPanel5.setMinimumSize(new java.awt.Dimension(483, 104));
        jPanel5.setPreferredSize(new java.awt.Dimension(483, 104));

        btnQuit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gui/img/Quit.png"))); // NOI18N
        btnQuit.setToolTipText("Quit");
        btnQuit.setBorderPainted(false);
        btnQuit.setMaximumSize(new java.awt.Dimension(64, 64));
        btnQuit.setMinimumSize(new java.awt.Dimension(64, 64));
        btnQuit.setPreferredSize(new java.awt.Dimension(64, 64));
        btnQuit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnQuitMouseClicked(evt);
            }
        });

        btnWriteContract.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gui/img/Contract.png"))); // NOI18N
        btnWriteContract.setToolTipText("Write Contract");
        btnWriteContract.setBorderPainted(false);
        btnWriteContract.setMaximumSize(new java.awt.Dimension(64, 64));
        btnWriteContract.setMinimumSize(new java.awt.Dimension(64, 64));
        btnWriteContract.setPreferredSize(new java.awt.Dimension(64, 64));
        btnWriteContract.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnWriteContractMouseClicked(evt);
            }
        });
        btnWriteContract.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnWriteContractKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnWriteContract, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 331, Short.MAX_VALUE)
                .addComponent(btnQuit, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnWriteContract, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnQuit, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtf_stockQuantityItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jtf_stockQuantityItemStateChanged
        totalPriceCalculator();
    }//GEN-LAST:event_jtf_stockQuantityItemStateChanged
    
    private void btnQuitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQuitMouseClicked
        dispose();
    }//GEN-LAST:event_btnQuitMouseClicked
    
    private void btnBetaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBetaMouseClicked
        jtfBeta.setText(roundDBL(stock.calculateMonthlyBeta(portfolio.getMarket().getMarketId())) + "");
        if (stock.getBeta() > 1) {
            jtfAgr.setBackground(new Color(254,33,94));
            jtfCon.setBackground(conColor);
        } else {
            jtfAgr.setBackground(agrColor);
            jtfCon.setBackground(new Color(55, 185, 255));
        }
    }//GEN-LAST:event_btnBetaMouseClicked
    
    private void btnWriteContractKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnWriteContractKeyPressed
        
        if (!moneyError) {
            OrderStock orderStock = new OrderStock(Integer.parseInt(jtf_stockQuantity.getSelectedItem().toString()), stock);
            
            PortfolioPerformanceUtilities.getMe().manageBuyOrders(portfolio, orderStock);
            
            JOptionPane.showMessageDialog(this, "Buy order successful", "Buy Notification", JOptionPane.INFORMATION_MESSAGE);
            refresher();
            dispose();
            GUI.UpdateJTable(true, true, false, false);
            
        } else {
            JOptionPane.showMessageDialog(this,
                    "You Don't have enough money!", "Money Alert",
                    JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnWriteContractKeyPressed
    
    private void btnWriteContractMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnWriteContractMouseClicked
        
        if (!moneyError) {
            OrderStock orderStock = new OrderStock(Integer.parseInt(jtf_stockQuantity.getSelectedItem().toString()), stock);
            PortfolioPerformanceUtilities.getMe().manageBuyOrders(portfolio, orderStock);
            
            JOptionPane.showMessageDialog(this, "Buy order successful", "Buy Notification", JOptionPane.INFORMATION_MESSAGE);
            refresher();
            dispose();
            GUI.UpdateJTable(true, true, false, false);
        } else {
            JOptionPane.showMessageDialog(this,
                    "You Don't have enough money!", "Money Alert",
                    JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnWriteContractMouseClicked
    
    private static void totalPriceCalculator() {
        int quantity = Integer.parseInt(jtf_stockQuantity.getSelectedItem().toString());
        double totalPrice = stock.getBuyPrice() * quantity;
        jtf_stockPrice1.setText(moneyWriter(totalPrice));
        updatePortfolioDetails(totalPrice);
    }
    
    private static void updatePortfolioDetails(double totalPrice) {
        double portMoney = portfolio.getLiquidMoney() - totalPrice;
        double investedMoney = portfolio.getInvestedMoney() + totalPrice;
        
        if (portMoney < 0) {
            moneyError = true;
            jtf_balance.setBackground(Color.red);
        } else {
            moneyError = false;
            jtf_balance.setBackground(balColor);
            jtf_balance.setText(moneyWriter(portMoney));
            jtfInvestedMoney.setText(moneyWriter(investedMoney));
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderBuy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderBuy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderBuy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderBuy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrderBuy().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JButton btnBeta;
    private static javax.swing.JButton btnQuit;
    private static javax.swing.JButton btnWriteContract;
    private javax.swing.ButtonGroup buttonGroup1;
    private static javax.swing.JLabel jLabel1;
    private static javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private static javax.swing.JLabel jLabel2;
    private static javax.swing.JLabel jLabel3;
    private static javax.swing.JLabel jLabel4;
    private static javax.swing.JLabel jLabel5;
    private static javax.swing.JLabel jLabel6;
    private static javax.swing.JLabel jLabel7;
    private static javax.swing.JLabel jLabel8;
    private static javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private static javax.swing.JPanel jPanel2;
    private static javax.swing.JPanel jPanel3;
    private static javax.swing.JPanel jPanel4;
    private static javax.swing.JPanel jPanel5;
    private static javax.swing.JSeparator jSeparator1;
    private static javax.swing.JTextField jtfAgr;
    private static javax.swing.JTextField jtfBeta;
    private static javax.swing.JTextField jtfCon;
    private static javax.swing.JTextField jtfDate;
    private static javax.swing.JTextField jtfInvestedMoney;
    private static javax.swing.JTextField jtfMarket;
    private static javax.swing.JTextField jtfPerformance;
    private static javax.swing.JTextField jtfStock;
    private static javax.swing.JTextField jtf_balance;
    private static javax.swing.JTextField jtf_stockPrice;
    private static javax.swing.JTextField jtf_stockPrice1;
    private static javax.swing.JComboBox jtf_stockQuantity;
    // End of variables declaration//GEN-END:variables
}
