/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.PortfolioManager.businessGUI.portfolioManagement.gui;

import com.PortfolioManager.domain.dao.IAccountDAO;
import com.PortfolioManager.domain.dao.IPortfolioDAO;
import com.PortfolioManager.domain.entities.Account;
import com.PortfolioManager.domain.entities.Portfolio;
import com.PortfolioManager.domain.impl.AccountDAO;
import com.PortfolioManager.domain.impl.PortfolioDAO;
import com.gui.mainGUI.GUI;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;

/**
 *
 * @author Ahmed
 */
public class PortfolioSelection extends javax.swing.JFrame {

    /**
     * Creates new form PortfolioSelection
     */
    private static PortfolioSelection portfolioSelection;
    private static List<Portfolio> listPortfolios;
    private static Account account;

    public static PortfolioSelection getMe() {
        if (portfolioSelection == null) {
            portfolioSelection = new PortfolioSelection();
        }
        initPortfoliosList();
        initAccount();
        return portfolioSelection;
    }

    private PortfolioSelection() {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height
                / 2 - this.getSize().height / 2);
        account = new Account();
        account = GUI.getMe().getLoggedInvestor().getAccount();
    }

    public static void initPortfoliosList() {
        IPortfolioDAO portfolioDAO = new PortfolioDAO();
        cmb_portf.removeAllItems();
        listPortfolios = portfolioDAO.getPortfoliByAccount(GUI.getMe().getLoggedInvestor().getAccount().getId());
        for (Portfolio p : listPortfolios) {
            cmb_portf.addItem(p.getName());
        }
    }

    public static void initAccount() {
        account = GUI.getMe().getLoggedInvestor().getAccount();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        cmb_portf = new javax.swing.JComboBox();
        btnQuit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        btnSelect = new javax.swing.JButton();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Portfolio Selection");
        setAlwaysOnTop(true);
        setMinimumSize(new java.awt.Dimension(345, 300));
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Select a portfolio"));
        jPanel1.setMaximumSize(new java.awt.Dimension(325, 278));
        jPanel1.setMinimumSize(new java.awt.Dimension(325, 278));

        cmb_portf.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_portfItemStateChanged(evt);
            }
        });

        btnQuit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gui/img/exit_delete.png"))); // NOI18N
        btnQuit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnQuitMouseClicked(evt);
            }
        });
        btnQuit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnQuitKeyPressed(evt);
            }
        });

        jLabel1.setText("Portfolios list:");

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Invested Money", "Potential Returns", "Performance"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTable.setFocusable(false);
        jTable.setIntercellSpacing(new java.awt.Dimension(2, 2));
        jTable.setRowSelectionAllowed(false);
        jTable.getTableHeader().setResizingAllowed(false);
        jTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable);

        jLabel2.setText("Portfolio Properties:");

        btnSelect.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gui/img/yes.png"))); // NOI18N
        btnSelect.setSelected(true);
        btnSelect.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSelectMouseClicked(evt);
            }
        });
        btnSelect.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnSelectKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmb_portf, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(btnSelect))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(btnQuit)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(9, 9, 9)
                .addComponent(cmb_portf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSelect, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnQuit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnQuitKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnQuitKeyPressed
        this.setAlwaysOnTop(false);
        this.setVisible(false);
    }//GEN-LAST:event_btnQuitKeyPressed

    private void btnQuitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQuitMouseClicked
        this.setAlwaysOnTop(false);
        this.setVisible(false);
    }//GEN-LAST:event_btnQuitMouseClicked

    private void cmb_portfItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_portfItemStateChanged
        if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
            //table update
            IPortfolioDAO portfolioDAO = new PortfolioDAO();
            Portfolio portfolio = portfolioDAO.getPortfolioByName(cmb_portf.getSelectedItem().toString(), GUI.getMe().getLoggedInvestor().getAccount().getId());
            TableModel tableModel = jTable.getModel();
            tableModel.setValueAt(portfolio.getInvestedMoney(), 0, 0);
            tableModel.setValueAt(portfolio.getPotentialEarnings(), 0, 1);
            tableModel.setValueAt(portfolio.getPortfolioPerformance(), 0, 2);
            jTable.setModel(tableModel);
        }
    }//GEN-LAST:event_cmb_portfItemStateChanged

    private void btnSelectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSelectMouseClicked
        IPortfolioDAO portfolioDAO = new PortfolioDAO();
        Portfolio portfolio = portfolioDAO.getPortfolioByName(cmb_portf.getSelectedItem().toString(), account.getId());
        account.setSelectedPortfolio(portfolio.getId());
        IAccountDAO iAccountDAO = new AccountDAO();
        iAccountDAO.update(account);
        JOptionPane.showMessageDialog(this, "Portfolio: " + portfolio.getName() + " is selected!", "Portfolio selected", JOptionPane.INFORMATION_MESSAGE);
        GUI.getMe().getLoggedInvestor().getAccount().setSelectedPortfolio(portfolio.getId());
        GUI.getMe().getCmb_market().setSelectedItem(portfolio.getMarket().getMarketId());
        GUI.getMe().UpdateJTable(true, true, true,true);
        this.setAlwaysOnTop(false);
        this.setVisible(false);
    }//GEN-LAST:event_btnSelectMouseClicked

    private void btnSelectKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnSelectKeyPressed
        IPortfolioDAO portfolioDAO = new PortfolioDAO();
        Portfolio portfolio = portfolioDAO.getPortfolioByName(cmb_portf.getSelectedItem().toString(), account.getId());
        account.setSelectedPortfolio(portfolio.getId());
        IAccountDAO iAccountDAO = new AccountDAO();
        iAccountDAO.update(account);
        JOptionPane.showMessageDialog(this, "Portfolio: " + portfolio.getName() + " is selected!", "Portfolio selected", JOptionPane.INFORMATION_MESSAGE);
        GUI.getMe().getLoggedInvestor().getAccount().setSelectedPortfolio(portfolio.getId());
        GUI.getMe().getCmb_market().setSelectedItem(portfolio.getMarket().getMarketId());
        GUI.getMe().UpdateJTable(true, true, true,true);
        this.setAlwaysOnTop(false);
        this.setVisible(false);
    }//GEN-LAST:event_btnSelectKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PortfolioSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PortfolioSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PortfolioSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PortfolioSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PortfolioSelection().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JButton btnQuit;
    private static javax.swing.JButton btnSelect;
    private static javax.swing.JComboBox cmb_portf;
    private javax.swing.JComboBox jComboBox1;
    private static javax.swing.JLabel jLabel1;
    private static javax.swing.JLabel jLabel2;
    private static javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JTable jTable;
    // End of variables declaration//GEN-END:variables
}
