/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.PortfolioManager.businessGUI.portfolioManagement.gui;

import com.PortfolioManager.domain.dao.IAccountDAO;
import com.PortfolioManager.domain.dao.IMarket;
import com.PortfolioManager.domain.dao.IPortfolioDAO;
import com.PortfolioManager.domain.entities.Account;
import com.PortfolioManager.domain.entities.Market;
import com.PortfolioManager.domain.entities.PortfolioOperation;
import com.PortfolioManager.domain.entities.OrderStock;
import com.PortfolioManager.domain.entities.Portfolio;
import com.PortfolioManager.domain.entities.PortfolioHistory;
import com.PortfolioManager.domain.impl.AccountDAO;
import com.PortfolioManager.domain.impl.MarketDAO;
import com.PortfolioManager.domain.impl.PortfolioDAO;
import com.gui.mainGUI.GUI;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.math.BigDecimal;
import java.text.ParseException;
import java.util.Date;
import java.util.HashSet;
import java.util.StringTokenizer;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author Ahmed
 */
public class PortfolioCreation extends javax.swing.JFrame {

    private static PortfolioCreation portfolioCreation;
    private static MaskFormatter moneyMask;
    private static IAccountDAO iAccountDAO;
    private static Account account;
    private static Color c1;
    private static Color c2;
    private static Color c3;
    private static boolean nameError;
    private static boolean moneyError;
    private static boolean marketError;

    public static PortfolioCreation getMe() {
        if (portfolioCreation == null) {
            portfolioCreation = new PortfolioCreation();
        }
        reset();

        return portfolioCreation;
    }
    private MaskFormatter interestRate;

    /**
     * Creates new form PortfolioCreation
     */
    private PortfolioCreation() {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height
                / 2 - this.getSize().height / 2);
        init();
        iAccountDAO = new AccountDAO();
        c1 = jtfPortName.getBackground();
        c2 = jtfPortName.getForeground();
        c3 = jtfInvestMoney.getBackground();
        //
        jtfInvestMoney.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                updateLabel(e);
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                updateLabel(e);
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                updateLabel(e);
            }

            private void updateLabel(DocumentEvent e) {

                java.awt.EventQueue.invokeLater(new Runnable() {
                    @Override
                    public void run() {
                        double value = account.getMoney();
                        double valueInvested = moneyReader(jtfInvestMoney.getText());
                        value -= moneyReader(jtfInvestMoney.getText());
                        if (value < 0 || valueInvested < 500) {
                            jtfInvestMoney.setBackground(new Color(255, 0, 0));
                            moneyError = true;
                        } else {
                            jtfInvestMoney.setBackground(c3);
                            moneyError = false;
                            jtfAccountMoney.setText(moneyWriter(value));
                        }
                    }
                });
            }
        });
        //
    }

    public static void reset() {
        jtfInvestMoney.setText("");
        jtfPortName.setText("");
        jtfPortName.setBackground(c1);
        jtfPortName.setForeground(c2);
        jtfInvestMoney.setBackground(c3);
        jtfInterestRate.setText("");
        nameError = false;
        marketError = false;
        moneyError = false;
        account = GUI.getMe().getLoggedInvestor().getAccount();
        if (account.getMoney() < 500) {
            btnCreate.setEnabled(false);
        }
        jtfAccountMoney.setText(account.getMoney() + "");

    }

    public static void init() {
        cmb_markets.setModel(GUI.getCmb_market().getModel());
        reset();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cmb_markets = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jtfPortName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        try {             moneyMask = new MaskFormatter("###,###.##");             moneyMask.setPlaceholderCharacter('$');         } catch (ParseException e) {             e.printStackTrace();         }
        jtfInvestMoney =  new javax.swing.JFormattedTextField(moneyMask);
        jtfAccountMoney = new javax.swing.JTextField();
        jtfAccountMoney.setEditable(false);
        jLabel4 = new javax.swing.JLabel();
        btnReset = new javax.swing.JButton();
        btnCreate = new javax.swing.JButton();
        btnQuit = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        try {
            interestRate = new MaskFormatter("0.###"); 
            interestRate.setPlaceholderCharacter('$');         
        }
        catch (ParseException e) {             
            e.printStackTrace();         
        }
        jtfInterestRate =  new javax.swing.JFormattedTextField(interestRate);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Portfolio Creation");
        setAlwaysOnTop(true);
        setMinimumSize(new java.awt.Dimension(270, 385));
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Create New Portfolio", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 0, 11))); // NOI18N
        jPanel1.setMaximumSize(new java.awt.Dimension(250, 363));
        jPanel1.setMinimumSize(new java.awt.Dimension(250, 363));

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel1.setText("Market:");

        cmb_markets.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        cmb_markets.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "France_Paris_CAC40", "US_Nasdaq_NDX" }));
        cmb_markets.setMaximumSize(new java.awt.Dimension(218, 22));
        cmb_markets.setMinimumSize(new java.awt.Dimension(218, 22));
        cmb_markets.setPreferredSize(new java.awt.Dimension(218, 22));

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel2.setText("Portfolio Name:");

        jtfPortName.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jtfPortName.setMaximumSize(new java.awt.Dimension(218, 20));
        jtfPortName.setMinimumSize(new java.awt.Dimension(218, 20));
        jtfPortName.setPreferredSize(new java.awt.Dimension(218, 20));
        jtfPortName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfPortNameFocusLost(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Invested Money:");

        jtfInvestMoney.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jtfInvestMoney.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtfInvestMoney.setMaximumSize(new java.awt.Dimension(100, 26));
        jtfInvestMoney.setMinimumSize(new java.awt.Dimension(100, 26));
        jtfInvestMoney.setPreferredSize(new java.awt.Dimension(100, 26));

        jtfAccountMoney.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jtfAccountMoney.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtfAccountMoney.setMaximumSize(new java.awt.Dimension(100, 26));
        jtfAccountMoney.setMinimumSize(new java.awt.Dimension(100, 26));
        jtfAccountMoney.setPreferredSize(new java.awt.Dimension(100, 26));

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Account Balance:");

        btnReset.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gui/img/refresh.png"))); // NOI18N
        btnReset.setMnemonic('r');
        btnReset.setToolTipText("Reset");
        btnReset.setMaximumSize(new java.awt.Dimension(67, 23));
        btnReset.setMinimumSize(new java.awt.Dimension(67, 23));
        btnReset.setPreferredSize(new java.awt.Dimension(67, 23));
        btnReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnResetMouseClicked(evt);
            }
        });

        btnCreate.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btnCreate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gui/img/add.png"))); // NOI18N
        btnCreate.setMnemonic('c');
        btnCreate.setToolTipText("Create");
        btnCreate.setMaximumSize(new java.awt.Dimension(67, 23));
        btnCreate.setMinimumSize(new java.awt.Dimension(67, 23));
        btnCreate.setPreferredSize(new java.awt.Dimension(67, 23));
        btnCreate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCreateMouseClicked(evt);
            }
        });
        btnCreate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnCreateKeyPressed(evt);
            }
        });

        btnQuit.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btnQuit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gui/img/exit_delete.png"))); // NOI18N
        btnQuit.setMnemonic('q');
        btnQuit.setToolTipText("Quit");
        btnQuit.setMaximumSize(new java.awt.Dimension(67, 23));
        btnQuit.setMinimumSize(new java.awt.Dimension(67, 23));
        btnQuit.setPreferredSize(new java.awt.Dimension(67, 23));
        btnQuit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnQuitMouseClicked(evt);
            }
        });

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("$");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("$");

        jLabel7.setText("4 weeks Riskless Interest Rate:");

        jtfInterestRate.setToolTipText("http://www.federalreserve.gov/Releases/h15/update/");
        jtfInterestRate.setMaximumSize(new java.awt.Dimension(100, 20));
        jtfInterestRate.setMinimumSize(new java.awt.Dimension(100, 20));
        jtfInterestRate.setPreferredSize(new java.awt.Dimension(100, 20));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cmb_markets, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jtfPortName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnQuit, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfAccountMoney, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfInvestMoney, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jtfInterestRate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(42, 42, 42))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfPortName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(7, 7, 7)
                .addComponent(cmb_markets, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfInterestRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfInvestMoney, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfAccountMoney, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnQuit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResetMouseClicked
        reset();
    }//GEN-LAST:event_btnResetMouseClicked

    private void btnCreateKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnCreateKeyPressed
        if (!moneyError && !nameError && !marketError) {
            Portfolio portfolio = new Portfolio();

            portfolio.setOperations(new HashSet<PortfolioOperation>());
            portfolio.setOrderStocks(new HashSet<OrderStock>());
            portfolio.setPortfolioHistory(new HashSet<PortfolioHistory>());
            portfolio.setLiquidMoney(moneyReader(jtfInvestMoney.getText()));
            portfolio.setInitialMoney(moneyReader(jtfInvestMoney.getText()));
            portfolio.setInvestedMoney(0.0);
            portfolio.setPotentialEarnings(0.0);
            portfolio.setRIRate(Double.parseDouble(jtfInterestRate.getText().toString()));

            IMarket iMarket = new MarketDAO();
            Market market = iMarket.getMarketById(cmb_markets.getSelectedItem().toString());

            portfolio.setMarket(market);
            portfolio.setName(jtfPortName.getText());

            PortfolioHistory portfolioHistory = new PortfolioHistory();
            portfolioHistory.setMonthOfReturn(new Date());
            portfolioHistory.setPortfolioInitalMoney(portfolio.getInitialMoney());
            portfolioHistory.setPortfolioTodayValue(portfolio.getInitialMoney());
            portfolioHistory.setRIRate(portfolio.getRIRate());
            portfolio.addPortfolioHistory(portfolioHistory);

            account.addPortfolio(portfolio);
            iAccountDAO.update(account);
            JOptionPane.showMessageDialog(this, "Mr." + GUI.getMe().getLoggedInvestor().getLastName() + "Portfolio Added", "Portfolio Created Successfully", JOptionPane.INFORMATION_MESSAGE);
            GUI.getMe().UpdateJTable(true, true, true, true);
            GUI.getMe().enabler(true);
            reset();
        }
    }//GEN-LAST:event_btnCreateKeyPressed

    private void btnCreateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCreateMouseClicked
        if (!moneyError && !nameError && !marketError) {
            Portfolio portfolio = new Portfolio();

            portfolio.setOperations(new HashSet<PortfolioOperation>());
            portfolio.setOrderStocks(new HashSet<OrderStock>());
            portfolio.setPortfolioHistory(new HashSet<PortfolioHistory>());
            portfolio.setLiquidMoney(moneyReader(jtfInvestMoney.getText()));
            portfolio.setInitialMoney(moneyReader(jtfInvestMoney.getText()));
            portfolio.setInvestedMoney(0.0);
            portfolio.setPotentialEarnings(0.0);
            portfolio.setRIRate(Double.parseDouble(jtfInterestRate.getText().toString()));

            IMarket iMarket = new MarketDAO();
            Market market = iMarket.getMarketById(cmb_markets.getSelectedItem().toString());

            portfolio.setMarket(market);
            portfolio.setName(jtfPortName.getText());

            PortfolioHistory portfolioHistory = new PortfolioHistory();
            portfolioHistory.setMonthOfReturn(new Date());
            portfolioHistory.setPortfolioInitalMoney(portfolio.getInitialMoney());
            portfolioHistory.setPortfolioTodayValue(portfolio.getInitialMoney());
            portfolioHistory.setRIRate(portfolio.getRIRate());
            portfolio.addPortfolioHistory(portfolioHistory);

            account.addPortfolio(portfolio);
            iAccountDAO.update(account);
            System.out.println("ahmed");
            JOptionPane.showMessageDialog(this, "Mr." + GUI.getMe().getLoggedInvestor().getLastName() + "Portfolio Added", "Portfolio Created Successfully", JOptionPane.INFORMATION_MESSAGE);
            GUI.getMe().UpdateJTable(true, true, true, true);
            reset();
        }
    }//GEN-LAST:event_btnCreateMouseClicked

    public double moneyReader(String moneyString) {
        StringTokenizer st = new StringTokenizer(moneyString, ",");
        if (moneyString.contains("$")) {
            return 0.0;
        } else {
            double money = Double.parseDouble(st.nextToken()) * 1000;
            money += Double.parseDouble(st.nextToken());
            return money;
        }
    }

    public double roundDBL(double dollars) {
        int decimalPlace = 2;
        BigDecimal bd = new BigDecimal(dollars);
        bd = bd.setScale(decimalPlace, BigDecimal.ROUND_UP);

        return (bd.doubleValue());
    }

    public String moneyWriter(double moneyValue) {
        String money = "";
        int millions = (int) moneyValue / 1000;
        money += millions + ",";
        double dollars = moneyValue - millions * 1000;
        dollars = roundDBL(dollars);
        if (dollars < 10) {
            money += "00" + dollars;
        } else if (dollars < 100) {
            money += "0" + dollars;
        } else {
            money += "" + dollars;
        }
        return money;
    }
    private void btnQuitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQuitMouseClicked
        reset();
        setAlwaysOnTop(false);

        setVisible(false);
    }//GEN-LAST:event_btnQuitMouseClicked

    private void jtfPortNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfPortNameFocusLost
        if (account.getPortfolios().size() != 0 && !jtfPortName.getText().isEmpty()) {
            IPortfolioDAO portfolioDAO = new PortfolioDAO();
            if (portfolioDAO.getPortfolioByName(jtfPortName.getText().toString(), account.getId()) != null) {
                jtfPortName.setBackground(new Color(255, 0, 0));
                jtfPortName.setForeground(new Color(0, 124, 120));
                nameError = true;
            } else {
                jtfPortName.setBackground(c1);
                jtfPortName.setForeground(c2);
                nameError = false;
            }
        }
    }//GEN-LAST:event_jtfPortNameFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PortfolioCreation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PortfolioCreation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PortfolioCreation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PortfolioCreation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PortfolioCreation().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JButton btnCreate;
    private static javax.swing.JButton btnQuit;
    private static javax.swing.JButton btnReset;
    private static javax.swing.JComboBox cmb_markets;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private static javax.swing.JTextField jtfAccountMoney;
    private static javax.swing.JTextField jtfInterestRate;
    private static javax.swing.JTextField jtfInvestMoney;
    private static javax.swing.JTextField jtfPortName;
    // End of variables declaration//GEN-END:variables
}
