/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.PortfolioManager.businessGUI.accountManagement;

import com.PortfolioManager.domain.dao.IInvestorDAO;
import com.PortfolioManager.domain.entities.Investor;
import com.PortfolioManager.domain.impl.InvestorDAO;
import com.gui.mainGUI.GUI;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 * 
 * @author Ahmed
 */
public class AccoutRemove extends javax.swing.JFrame {

	/**
	 * Creates new form AccoutRemove
	 */
	private static AccoutRemove accoutRemove;

	private AccoutRemove() {
		initComponents();
		Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
		this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height
				/ 2 - this.getSize().height / 2);
	}

	public static AccoutRemove getMe() {
		if (accoutRemove == null)
			accoutRemove = new AccoutRemove();
		return accoutRemove;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanel3 = new javax.swing.JPanel();
		jLabel5 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		jButtonDelete = new javax.swing.JButton();
		jButtonQuit = new javax.swing.JButton();
		tfPwd = new javax.swing.JTextField();
		jPasswordField = new javax.swing.JPasswordField();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
		setMinimumSize(new java.awt.Dimension(250, 172));

		jPanel3.setBorder(javax.swing.BorderFactory
				.createTitledBorder("Enter login and password to delete account"));
		jPanel3.setMaximumSize(new java.awt.Dimension(250, 161));
		jPanel3.setMinimumSize(new java.awt.Dimension(250, 161));

		jLabel5.setText("Login:");

		jLabel6.setText("Password:");

		jButtonDelete.setText("Delete");
		jButtonDelete.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jButtonDeleteMouseClicked(evt);
			}
		});

		jButtonQuit.setText("Quit");
		jButtonQuit.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jButtonQuitMouseClicked(evt);
			}
		});
		jButtonQuit.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonQuitActionPerformed(evt);
			}
		});

		tfPwd.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				tfPwdActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(
				jPanel3);
		jPanel3.setLayout(jPanel3Layout);
		jPanel3Layout
				.setHorizontalGroup(jPanel3Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel3Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanel3Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(jLabel6)
														.addComponent(jLabel5))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addGroup(
												jPanel3Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																false)
														.addComponent(
																jPasswordField,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																80,
																Short.MAX_VALUE)
														.addComponent(tfPwd))
										.addContainerGap(88, Short.MAX_VALUE))
						.addGroup(
								jPanel3Layout
										.createSequentialGroup()
										.addComponent(jButtonDelete)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)
										.addComponent(
												jButtonQuit,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												63,
												javax.swing.GroupLayout.PREFERRED_SIZE)));
		jPanel3Layout
				.setVerticalGroup(jPanel3Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel3Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanel3Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																tfPwd,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel5))
										.addGap(18, 18, 18)
										.addGroup(
												jPanel3Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																jPasswordField,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel6))
										.addGap(18, 18, 18)
										.addGroup(
												jPanel3Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																jButtonQuit)
														.addComponent(
																jButtonDelete))
										.addContainerGap(25, Short.MAX_VALUE)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel3, javax.swing.GroupLayout.Alignment.TRAILING,
				javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup()
						.addContainerGap()
						.addComponent(jPanel3,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void jButtonQuitMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jButtonQuitMouseClicked
		reset();
		this.setVisible(false);

	}// GEN-LAST:event_jButtonQuitMouseClicked

	private void tfPwdActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_tfPwdActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_tfPwdActionPerformed

	private static void jButtonDeleteMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jButtonDeleteMouseClicked
		Investor investor = GUI.getMe().getLoggedInvestor();
		if (!tfPwd.getText().equals(investor.getLogin())
				|| !jPasswordField.getText().equals(investor.getPassword())) {
			JOptionPane.showMessageDialog(null, "Check Login or passord!",
					"Authorisation Failed", JOptionPane.ERROR_MESSAGE);
		} else {
			int response = JOptionPane
					.showConfirmDialog(
							accoutRemove,
							" Do you want to delete your account?\nAll the data will be removed.",
							"Warning!", JOptionPane.YES_NO_OPTION,
							JOptionPane.WARNING_MESSAGE);
			if (response != JOptionPane.YES_OPTION) {
				return;
			} else {
				IInvestorDAO iInvestorDAO=new InvestorDAO();
				iInvestorDAO.delete(investor);
				
				GUI.getMe().loggedInvestor=null;
				GUI.getMe().logged=2;
				
//				GUI.getMe().jTable2Portfolio.setModel(new javax.swing.table.DefaultTableModel(
//						new Object[1][1], new String[] { "Balance", "Invested Money",
//								"Returns", "Performance" }));
//				GUI.getMe().jTable1Orders.setModel(new javax.swing.table.DefaultTableModel(
//						new Object[1][1], new String[] { "Order Number", "Date",
//								"Stock", "Quantity", "Price", "Potential Returns" }));
				GUI.getMe().jTabbedPaneTables.revalidate();
				
				JOptionPane.showMessageDialog(accoutRemove, "Account Removed successfully",
						"Account Removed", JOptionPane.WARNING_MESSAGE);
				GUI.getMe().enabler(false);
				AccoutRemove.getMe().dispose();
				
			}
		}
	}// GEN-LAST:event_jButtonDeleteMouseClicked

	private void jButtonQuitActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonQuitActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jButtonQuitActionPerformed

	private void reset() {
		this.tfPwd.setText("");
		this.jPasswordField.setText("");
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed"
		// desc=" Look and feel setting code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase
		 * /tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
					.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(AccoutRemove.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(AccoutRemove.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(AccoutRemove.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(AccoutRemove.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new AccoutRemove().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private static javax.swing.JButton jButtonDelete;
	private static javax.swing.JButton jButtonQuit;
	private static javax.swing.JLabel jLabel5;
	private static javax.swing.JLabel jLabel6;
	private static javax.swing.JPanel jPanel3;
	private static javax.swing.JPasswordField jPasswordField;
	private static javax.swing.JTextField tfPwd;
	// End of variables declaration//GEN-END:variables
}
