/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.PortfolioManager.businessGUI.accountManagement;

import com.PortfolioManager.domain.dao.IConsultant;
import com.PortfolioManager.domain.dao.IInvestorDAO;
import com.PortfolioManager.domain.entities.Account;
import com.PortfolioManager.domain.entities.Consultant;
import com.PortfolioManager.domain.entities.Investor;
import com.PortfolioManager.domain.impl.ConsultantDAO;
import com.PortfolioManager.domain.impl.InvestorDAO;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.math.BigDecimal;
import java.text.ParseException;
import java.util.List;
import java.util.StringTokenizer;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author Ahmed
 */
public class CreateAccount extends javax.swing.JFrame {

    /**
     * Creates new form CreateAccount
     */
    private static CreateAccount accountCreation;
    private static MaskFormatter mobileMask;

    private CreateAccount() {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height
                / 2 - this.getSize().height / 2);
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gui/img/security-policies-icon.png"))); // NOI18N

        // upload Consultants from database
        cbxConsultant.removeAll();
        IConsultant iConsultant = new ConsultantDAO();
        List<Consultant> list = iConsultant.getAllConsultant();
        for (Consultant c : list) {
            cbxConsultant.addItem(c.getName());
        }
        // upload Consultants from database

    }

    public static CreateAccount getMe() {
        if (accountCreation == null) {
            accountCreation = new CreateAccount();
        }
        accountCreation.repaint();
        return accountCreation;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtfName = new javax.swing.JTextField();
        jtfLastName = new javax.swing.JTextField();
        jtfEmail = new javax.swing.JTextField();
        // /phone number mask 		
        try {
            mobileMask = new MaskFormatter("+###-##-###-###");
            mobileMask.setPlaceholderCharacter(' ');
        } 
        catch (ParseException e) {
            e.printStackTrace();
        } 		
        // /phone number mask==>>
        jtfMobile =  new javax.swing.JFormattedTextField(mobileMask);
        jLabel5 = new javax.swing.JLabel();
        jrbConsultants = new javax.swing.JRadioButton();
        cbxConsultant = new javax.swing.JComboBox();
        cmb_money = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tfPwd = new javax.swing.JPasswordField();
        tfLogin = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Account Creation");
        setAlwaysOnTop(true);
        setMaximumSize(new java.awt.Dimension(400, 475));
        setMinimumSize(new java.awt.Dimension(400, 475));
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Account Creation"));
        jPanel1.setMaximumSize(new java.awt.Dimension(380, 453));
        jPanel1.setMinimumSize(new java.awt.Dimension(380, 453));

        jLabel1.setText("First Name:");

        jLabel2.setText("Last Name:");

        jLabel3.setText("Email:");

        jLabel4.setText("Mobile:");

        jtfName.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jtfName.setText(" ");
        jtfName.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 153, 255), java.awt.Color.lightGray, new java.awt.Color(0, 153, 153), java.awt.Color.gray));
        jtfName.setMaximumSize(new java.awt.Dimension(150, 20));
        jtfName.setMinimumSize(new java.awt.Dimension(150, 20));
        jtfName.setPreferredSize(new java.awt.Dimension(150, 20));

        jtfLastName.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jtfLastName.setText(" ");
        jtfLastName.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 153, 255), java.awt.Color.lightGray, new java.awt.Color(0, 153, 153), java.awt.Color.gray));
        jtfLastName.setMaximumSize(new java.awt.Dimension(150, 20));
        jtfLastName.setMinimumSize(new java.awt.Dimension(150, 20));
        jtfLastName.setPreferredSize(new java.awt.Dimension(150, 20));

        jtfEmail.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jtfEmail.setText(" ");
        jtfEmail.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 153, 255), java.awt.Color.lightGray, new java.awt.Color(0, 153, 153), java.awt.Color.gray));
        jtfEmail.setMaximumSize(new java.awt.Dimension(210, 20));
        jtfEmail.setMinimumSize(new java.awt.Dimension(210, 20));
        jtfEmail.setPreferredSize(new java.awt.Dimension(210, 20));

        jtfMobile.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jtfMobile.setText(" ");
        jtfMobile.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 153, 255), java.awt.Color.lightGray, new java.awt.Color(0, 153, 153), java.awt.Color.gray));
        jtfMobile.setMaximumSize(new java.awt.Dimension(150, 20));
        jtfMobile.setMinimumSize(new java.awt.Dimension(150, 20));
        jtfMobile.setPreferredSize(new java.awt.Dimension(150, 20));

        jLabel5.setText("Debit Account:     $");

        jrbConsultants.setText("Consultant:");
        jrbConsultants.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jrbConsultantsItemStateChanged(evt);
            }
        });

        cbxConsultant.setEnabled(false);

        cmb_money.setBackground(new java.awt.Color(166, 210, 255));
        cmb_money.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        cmb_money.setMaximumRowCount(5);
        cmb_money.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "5,000.00", "10,000.00", "15,000.00", "20,000.00", "25,000.00", "30,000.00", "35,000.00", "40,000.00", "45,000.00", "50,000.00", "100,000.00", "150,000.00", "200,000.00", "250,000.00", "300,000.00", "350,000.00", "400,000.00", "450,000.00", "500,000.00" }));
        cmb_money.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cmb_money.setLightWeightPopupEnabled(false);
        cmb_money.setMaximumSize(new java.awt.Dimension(110, 22));
        cmb_money.setMinimumSize(new java.awt.Dimension(110, 22));
        cmb_money.setPreferredSize(new java.awt.Dimension(110, 22));

        jLabel6.setText("Login:");

        jLabel7.setText("Password:");

        tfPwd.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tfPwd.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 153, 255), java.awt.Color.lightGray, new java.awt.Color(0, 153, 153), java.awt.Color.gray));
        tfPwd.setMaximumSize(new java.awt.Dimension(110, 20));
        tfPwd.setMinimumSize(new java.awt.Dimension(110, 20));
        tfPwd.setPreferredSize(new java.awt.Dimension(110, 20));

        tfLogin.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tfLogin.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 153, 255), java.awt.Color.lightGray, new java.awt.Color(0, 153, 153), java.awt.Color.gray));
        tfLogin.setMaximumSize(new java.awt.Dimension(110, 20));
        tfLogin.setMinimumSize(new java.awt.Dimension(110, 20));
        tfLogin.setPreferredSize(new java.awt.Dimension(110, 20));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gui/img/security-policies-icon.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setFocusPainted(false);
        jButton1.setFocusable(false);
        jButton1.setMaximumSize(new java.awt.Dimension(64, 64));
        jButton1.setMinimumSize(new java.awt.Dimension(64, 64));
        jButton1.setPreferredSize(new java.awt.Dimension(64, 64));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gui/img/Security.png"))); // NOI18N
        jButton2.setBorderPainted(false);
        jButton2.setFocusPainted(false);
        jButton2.setFocusable(false);
        jButton2.setMaximumSize(new java.awt.Dimension(48, 48));
        jButton2.setMinimumSize(new java.awt.Dimension(48, 48));
        jButton2.setPreferredSize(new java.awt.Dimension(48, 48));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gui/img/App-wallet-dark-icon.png"))); // NOI18N
        jButton3.setBorderPainted(false);
        jButton3.setFocusPainted(false);
        jButton3.setFocusable(false);
        jButton3.setMaximumSize(new java.awt.Dimension(64, 64));
        jButton3.setMinimumSize(new java.awt.Dimension(64, 64));
        jButton3.setPreferredSize(new java.awt.Dimension(64, 64));

        jButton4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gui/img/add.png"))); // NOI18N
        jButton4.setToolTipText("Create");
        jButton4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 153, 255), java.awt.Color.lightGray, new java.awt.Color(0, 153, 204), java.awt.Color.gray));
        jButton4.setMaximumSize(new java.awt.Dimension(65, 23));
        jButton4.setMinimumSize(new java.awt.Dimension(65, 23));
        jButton4.setPreferredSize(new java.awt.Dimension(65, 23));
        jButton4.setSelected(true);
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jButton4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton4KeyPressed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gui/img/exit_delete.png"))); // NOI18N
        jButton5.setToolTipText("Quit");
        jButton5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 153, 255), java.awt.Color.lightGray, new java.awt.Color(0, 153, 204), java.awt.Color.gray));
        jButton5.setMaximumSize(new java.awt.Dimension(65, 23));
        jButton5.setMinimumSize(new java.awt.Dimension(65, 23));
        jButton5.setPreferredSize(new java.awt.Dimension(65, 23));
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gui/img/refresh.png"))); // NOI18N
        jButton6.setToolTipText("Reset");
        jButton6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 153, 255), java.awt.Color.lightGray, new java.awt.Color(0, 153, 204), java.awt.Color.gray));
        jButton6.setMaximumSize(new java.awt.Dimension(65, 23));
        jButton6.setMinimumSize(new java.awt.Dimension(65, 23));
        jButton6.setPreferredSize(new java.awt.Dimension(65, 23));
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jrbConsultants)
                                .addGap(18, 18, 18)
                                .addComponent(cbxConsultant, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfPwd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jtfMobile, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmb_money, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator3)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jtfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jtfLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jtfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtfMobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmb_money, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jrbConsultants)
                        .addComponent(cbxConsultant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(tfLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(tfPwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton4KeyPressed

        Investor investor = new Investor();
        Account account;
        IInvestorDAO iInvestorDAO = new InvestorDAO();
        investor.setLogin(tfLogin.getText());
        if (iInvestorDAO.getInvestorById(tfLogin.getText()) == null) {
            if (tfPwd.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Password required!",
                        "Infilled required Information!!",
                        JOptionPane.ERROR_MESSAGE);
            } else if (tfPwd.getText().length() <= 4) {
                JOptionPane.showMessageDialog(this,
                        "Password must be longer than 4 characters!",
                        "Infilled required Information!!",
                        JOptionPane.ERROR_MESSAGE);
            } else if (jtfEmail.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this,
                        "Please insert your email address!",
                        "Infilled required Information!!",
                        JOptionPane.ERROR_MESSAGE);
            } else if (!validate(jtfEmail.getText())) {
                JOptionPane.showMessageDialog(this,
                        "Please enter a valid email address!",
                        "Infilled required Information!!",
                        JOptionPane.ERROR_MESSAGE);
            } else {
                investor.setName(jtfName.getText());
                investor.setLastName(jtfLastName.getText());
                investor.setEmail(jtfEmail.getText());

                if (!jtfMobile.getText().isEmpty()) {
                    // to delete - characters in the formattedJtextfield
                    StringTokenizer st = new StringTokenizer(jtfMobile.getText(),
                            "-");
                    String mobilePhone = st.nextToken() + st.nextToken()
                            + st.nextToken() + st.nextToken();
                    // to delete - characters in the formattedJtextfield

                    investor.setMobile(mobilePhone);
                }

                investor.setPassword(tfPwd.getText());

                account = new Account();
                String money = cmb_money.getSelectedItem().toString();

                account.setMoney(moneyReader(money));
                account.setInitialMoney(moneyReader(money));
                investor.setAccount(account);

                Consultant consultant;
                String consultantChosen = "";
                if (jrbConsultants.isSelected()) {

                    IConsultant iconsultant = new ConsultantDAO();
                    consultant = iconsultant.getConsultanttById(cbxConsultant
                            .getSelectedItem().toString());
                    investor.setConsultant(consultant);


                    EmailNotifier emailNotifier = new EmailNotifier();
                    emailNotifier.setFrom(investor.getEmail());
                    emailNotifier.setTo(consultant.getEmail());
                    emailNotifier.setBody(setEmailBody(investor, consultant));
                    emailNotifier.setSubject("New CSI client has chosen you");
                    emailNotifier.send();
                    consultantChosen = "\nAn email has been sent to your consultant";
                }

                iInvestorDAO.persist(investor);
                JOptionPane.showMessageDialog(this,
                        "Welcome! Please Log in to create a portfolio!" + consultantChosen,
                        "Welcome " + investor.getLogin(),
                        JOptionPane.INFORMATION_MESSAGE);
                this.setVisible(false);
            }
        } else {
            JOptionPane.showMessageDialog(this, "This Login is Used",
                    "Existing Account!!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton4KeyPressed

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        Investor investor = new Investor();
        Account account;
        IInvestorDAO iInvestorDAO = new InvestorDAO();
        investor.setLogin(tfLogin.getText());
        if (iInvestorDAO.getInvestorById(tfLogin.getText()) == null) {
            if (tfPwd.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Password required!",
                        "Infilled required Information!!",
                        JOptionPane.ERROR_MESSAGE);
            } else if (tfPwd.getText().length() <= 4) {
                JOptionPane.showMessageDialog(this,
                        "Password must be longer than 4 characters!",
                        "Infilled required Information!!",
                        JOptionPane.ERROR_MESSAGE);
            } else if (jtfEmail.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this,
                        "Please insert your email address!",
                        "Infilled required Information!!",
                        JOptionPane.ERROR_MESSAGE);
            } else if (!validate(jtfEmail.getText())) {
                JOptionPane.showMessageDialog(this,
                        "Please enter a valid email address!",
                        "Infilled required Information!!",
                        JOptionPane.ERROR_MESSAGE);
            } else {
                investor.setName(jtfName.getText());
                investor.setLastName(jtfLastName.getText());
                investor.setEmail(jtfEmail.getText());

                if (!jtfMobile.getText().isEmpty()) {
                    // to delete - characters in the formattedJtextfield
                    StringTokenizer st = new StringTokenizer(jtfMobile.getText(),
                            "-");
                    String mobilePhone = st.nextToken() + st.nextToken()
                            + st.nextToken() + st.nextToken();
                    // to delete - characters in the formattedJtextfield

                    investor.setMobile(mobilePhone);
                }

                investor.setPassword(tfPwd.getText());

                account = new Account();
                String money = cmb_money.getSelectedItem().toString();

                account.setMoney(moneyReader(money));
                account.setInitialMoney(moneyReader(money));
                investor.setAccount(account);

                Consultant consultant;
                String consultantChosen = "";
                if (jrbConsultants.isSelected()) {

                    IConsultant iconsultant = new ConsultantDAO();
                    consultant = iconsultant.getConsultanttById(cbxConsultant
                            .getSelectedItem().toString());
                    investor.setConsultant(consultant);


                    EmailNotifier emailNotifier = new EmailNotifier();
                    emailNotifier.setFrom(investor.getEmail());
                    emailNotifier.setTo(consultant.getEmail());
                    emailNotifier.setBody(setEmailBody(investor, consultant));
                    emailNotifier.setSubject("New CSI client has chosen you");
                    emailNotifier.send();
                    consultantChosen = "\nAn email has been sent to your consultant";
                }

                iInvestorDAO.persist(investor);
                JOptionPane.showMessageDialog(this,
                        "Welcome! Please Log in to create a portfolio!" + consultantChosen,
                        "Welcome " + investor.getLogin(),
                        JOptionPane.INFORMATION_MESSAGE);
                this.setVisible(false);
            }
        } else {
            JOptionPane.showMessageDialog(this, "This Login is Used",
                    "Existing Account!!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        reset();
    }//GEN-LAST:event_jButton6MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        this.reset();// if not, when you quit and then reenter the account
        // interface
        // you'll find the text you edited : not nice ;)
        this.setVisible(false);
    }//GEN-LAST:event_jButton5MouseClicked

    private void jrbConsultantsItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jrbConsultantsItemStateChanged
        if (jrbConsultants.isSelected()) {
            cbxConsultant.enable();
        } else {
            cbxConsultant.disable();
        }
    }//GEN-LAST:event_jrbConsultantsItemStateChanged

    public double moneyReader(String moneyString) {
        StringTokenizer st = new StringTokenizer(moneyString, ",");
        if (moneyString.contains("$")) {
            return 0.0;
        } else {
            double money = Double.parseDouble(st.nextToken()) * 1000;
            money += Double.parseDouble(st.nextToken());
            return money;
        }
    }

    public double roundDBL(double dollars) {
        int decimalPlace = 2;
        BigDecimal bd = new BigDecimal(dollars);
        bd = bd.setScale(decimalPlace, BigDecimal.ROUND_UP);

        return (bd.doubleValue());
    }

    public String moneyWriter(double moneyValue) {
        String money = "";
        int millions = (int) moneyValue / 1000;
        money += millions + ",";
        double dollars = moneyValue - millions * 1000;
        dollars = roundDBL(dollars);
        if (dollars < 10) {
            money += "00" + dollars;
        } else if (dollars < 100) {
            money += "0" + dollars;
        } else {
            money += "" + dollars;
        }
        return money;
    }

    private String setEmailBody(Investor investor, Consultant consultant) {
        String boddy, body = new String();
        String hello = "Dear Mr" + consultant.getName() + ",\n";
        boddy = "CSI System is notifying you that Mr " + investor.getName() + " " + investor.getLastName() + " has chosen you to be his C.S.I. consultant.\n\n";
        boddy += "\nPlease you're invited to reply to his request within 24hours.";
        boddy += "\nAccount balance:[$ " + investor.getAccount().displayMoney() + "]\n\n";
        boddy += "\n$$$ This EMAIL WAS AUTOGENERATED BY C.S.I. SYSTEM ROUTINES $$$";
        boddy += "\n       $$$ IT IS MOST LIKELY TO BE SHOWN AS SPAM $$$";
        boddy += "\n   $$$ IT IS RECOMMANDED THAT YOU MARK IT AS NOT SPAM $$$";
        boddy += "\n                      $$$ THANK YOU $$$";
        boddy += "\n            $$$ C.S.I. SYSTEM YOUR WEALTH PARTNER $$$";
        body = hello + boddy;
        return body;
    }

    // email input control
    public boolean validate(final String email) {

        // email pattern to control email input
        String emailWatcher = "^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@"
                + "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$";
        // email pattern to control email input

        Pattern pattern = Pattern.compile(emailWatcher);
        Matcher matcher = pattern.matcher(email);
        return matcher.matches();
    }

    private void reset() {
        this.jtfName.setText("");
        this.jtfLastName.setText("");
        this.jtfEmail.setText("");
        this.tfLogin.setText("");
        this.jtfMobile.setText("");
        this.cmb_money.setSelectedIndex(0);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateAccount().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JComboBox cbxConsultant;
    private static javax.swing.JComboBox cmb_money;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private static javax.swing.JButton jButton4;
    private static javax.swing.JButton jButton5;
    private static javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private static javax.swing.JRadioButton jrbConsultants;
    private static javax.swing.JTextField jtfEmail;
    private static javax.swing.JTextField jtfLastName;
    private static javax.swing.JTextField jtfMobile;
    private static javax.swing.JTextField jtfName;
    private static javax.swing.JTextField tfLogin;
    private static javax.swing.JPasswordField tfPwd;
    // End of variables declaration//GEN-END:variables
}
